pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test Multi-Platform Images
            image: atlassian/default-image:4
            runs-on:
              - linux
              - self.hosted
            services:
              - docker
            script:
              - echo "Executing on self-hosted runner" 
              - export DOCKER_CLI_EXPERIMENTAL=enabled 
              - export BUILDX_VERSION=0.22.0
              
              - curl -fsSLO https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64
              - mkdir -p $HOME/.docker/cli-plugins/ && mv buildx-v${BUILDX_VERSION}.linux-amd64 $HOME/.docker/cli-plugins/docker-buildx && chmod +x ~/.docker/cli-plugins/docker-buildx
              
              - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
              - docker buildx create --use

              - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
        
              - IMAGE_NAME=$BITBUCKET_REPO_SLUG
              
              - docker buildx build --platform linux/amd64,linux/arm64 . --file Dockerfile --tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$BITBUCKET_BRANCH --push

definitions:
  services:
    docker:
      image: docker:dind