image: docker:28.0.4

pipelines:
  default:
    - step:
        name: Build and Push Docker Images
        caches:
          - docker
        script:
          # 启用 Docker Buildx
          - docker buildx create --use
          
          # 登录到 Docker Hub
          - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          
          # 构建并推送 AMD64 版本
          - docker buildx build --platform linux/amd64 -t $DOCKERHUB_USERNAME/$DOCKER_REPO:${BITBUCKET_BRANCH} . --push
          
          # 构建并推送 ARM64 版本
          - docker buildx build --platform linux/arm64 -t $DOCKERHUB_USERNAME/$DOCKER_REPO:${BITBUCKET_BRANCH} . --push
