{application,elixir_make,
             [{config_mtime,1734070221},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A Make compiler for Mix"},
              {modules,['Elixir.ElixirMake.Artefact',
                        'Elixir.ElixirMake.Compiler',
                        'Elixir.ElixirMake.Downloader',
                        'Elixir.ElixirMake.Downloader.Httpc',
                        'Elixir.ElixirMake.Precompiler',
                        'Elixir.Mix.Tasks.Compile.ElixirMake',
                        'Elixir.Mix.Tasks.ElixirMake.Checksum',
                        'Elixir.Mix.Tasks.ElixirMake.Precompile']},
              {registered,[]},
              {vsn,"0.9.0"}]}.
