import Config

# Configure your database
config :moly, Moly.Repo,
  username: "yukari",
  password: "83233167",
  hostname: "localhost",
  database: "moly_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :moly, MolyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "TZLcv1+vrTqQP328e/JPkafOivjqfZYGd1sXlvJS/aoGxs3RhId/BtaYJc2nyhMt",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:moly, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:moly, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :moly, MolyWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/moly_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :moly, dev_routes: true, token_signing_secret: "1xHm1M022NzBxpdFbFwS3u4t2M9uHpmd"

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Customize env for this app
config :moly,
  google_oauth2_client_id:
    "486343447885-9jg87vj9h0qafcdvu4k2ugb7dggbsion.apps.googleusercontent.com",
  google_oauth2_redirect_uri: "http://localhost:4000/auth/user/google/callback",
  google_oauth2_client_secret: "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",
  email_name: "moly@moly.dev",
  email_address: "moly@moly.dev",
  imagor_endpoint: "http://192.168.6.8:8000",
  imagor_secret: "WpozRdSDvTKVEPkOQ+/mSWEzIPdjXRFhYLB62XBN12knQ2SRvjMmsOJ/kNJT8UgI"

config :ex_aws,
  region: "us-east-1",
  access_key_id: "415efd2219d218600c53964e88d8fe82",
  secret_access_key: "78b72539f2b1daef78868904b452592790d62e00b404455e1a0384bd14f264bf"

config :ex_aws, :s3,
  scheme: "https://",
  host: "9a489bdeb68e9c3976091df2de6de7d8.r2.cloudflarestorage.com",
  port: 443,
  bucket: "moly-dev"

config :moly, Moly.Cluster,
  url: "https://localhost:9200",
  username: "elastic",
  password: "83233167",
  json_library: JSON,
  http_client_adapter: {Snap.HTTPClient.Adapters.Finch, [conn_opts: [transport_opts: [verify: :verify_none]]]}

#   domain: "192.168.6.8:9000/local", #set minio bucket public for accsess
#   domain_scheme: "http"

# config :imgproxy,
#   prefix: "http://192.168.6.8:8008",
#   key: "31dde3553997eb7bd3ad1ce2700c2f2e32dc15fffcd19969399e65b7c7d47c81",
#   salt: "38d48531bc85ac8273a0cb9f057223349141a53954937b97785b9cbf15ee34ee"
