defmodule Monorepo.Repo.Migrations.UserAddIsAdmin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :is_admin, :boolean, null: false, default: false
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :subject, :text, null: false
      add :cover_image, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id, :uuid
      add :user_id, :uuid
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:posts) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "posts_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "posts_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:categories) do
      add :category_name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:categories) do
      remove :updated_at
      remove :inserted_at
      remove :category_name
    end

    drop constraint(:posts, "posts_category_id_fkey")

    drop constraint(:posts, "posts_user_id_fkey")

    alter table(:posts) do
      modify :user_id, :uuid
      modify :category_id, :uuid
    end

    drop table(:categories)

    drop table(:posts)

    alter table(:users) do
      remove :is_admin
    end
  end
end
