defmodule Monorepo.Repo.Migrations.Initial4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      add(:category_type, :text, null: false, default: "blog")
    end
  end

  def down do
    alter table(:categories) do
      remove(:category_type)
    end
  end
end
