defmodule Monorepo.Repo.Migrations.AddProfileName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users_profiles) do
      add :username, :text, null: false
      add :name, :text
    end

    create unique_index(:users_profiles, [:username],
             name: "users_profiles_unique_username_index"
           )
  end

  def down do
    drop_if_exists unique_index(:users_profiles, [:username],
                     name: "users_profiles_unique_username_index"
                   )

    alter table(:users_profiles) do
      remove :name
      remove :username
    end
  end
end
