defmodule Monorepo.Repo.Migrations.Initial2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify(:role, :text, null: false, default: "user")
    end
  end

  def down do
    alter table(:users) do
      modify(:role, :text, null: true, default: nil)
    end
  end
end
