defmodule Monorepo.Repo.Migrations.AddUserProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "users_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :first_name, :text
      add :last_name, :text
      add :profile_picture, :text
      add :bio, :text
      add :date_of_birth, :date
      add :gender, :text
      add :phone_number, :text
      add :address, :text
      add :social_links, :map
      add :is_active, :boolean, default: true
      add :last_login_at, :naive_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:users_profiles, "users_profiles_user_id_fkey")

    drop table(:users_profiles)
  end
end
