defmodule Monorepo.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:confirmed_at, :utc_datetime_usec)
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)
      add(:roles, {:array, :text}, null: false)
      add(:status, :text, null: false, default: "inactive")
      add(:nickname, :text)
      add(:display_name, :text)
      add(:avatar, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:users, [:display_name], name: "users_unique_display_name_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:user_meta, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:meta_key, :text, null: false)
      add(:meta_value, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "user_meta_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:tokens, primary_key: false) do
      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:jti, :text, null: false, primary_key: true)
      add(:subject, :text, null: false)
      add(:expires_at, :utc_datetime, null: false)
      add(:purpose, :text, null: false)
      add(:extra_data, :map)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:terms, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:term_group, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:terms, [:slug], name: "terms_unique_slug_index")

    create table(:term_taxonomy, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:taxonomy, :text, null: false)
      add(:description, :text, null: false)
      add(:count, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :term_id,
        references(:terms,
          column: :id,
          name: "term_taxonomy_term_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :parent_id,
        references(:term_taxonomy,
          column: :id,
          name: "term_taxonomy_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:term_relationships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:term_order, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :term_taxonomy_id,
        references(:term_taxonomy,
          column: :id,
          name: "term_relationships_term_taxonomy_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:post_id, :uuid)
    end

    create table(:term_meta, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:term_key, :text, null: false)
      add(:term_value, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :term_id,
        references(:terms,
          column: :id,
          name: "term_meta_term_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:term_relationships) do
      modify(
        :post_id,
        references(:posts,
          column: :id,
          name: "term_relationships_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:posts) do
      add(:post_title, :text, null: false)
      add(:post_content, :text)
      add(:post_excerpt, :text)
      add(:post_status, :text, null: false, default: "draft")
      add(:post_type, :text, null: false, default: "post")
      add(:comment_status, :boolean, null: false, default: false)
      add(:ping_status, :boolean, null: false, default: false)
      add(:to_ping, {:array, :text}, null: false, default: [])
      add(:pinged, {:array, :text}, null: false, default: [])
      add(:guid, :text)
      add(:menu_order, :bigint, null: false, default: 0)
      add(:post_mime_type, :text, null: false, default: "post")
      add(:comment_count, :bigint, null: false, default: 0)
      add(:post_password, :text)
      add(:post_name, :text, null: false, default: "")
      add(:post_content_filtered, :text, default: "")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "posts_author_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :post_parent,
        references(:posts,
          column: :id,
          name: "posts_post_parent_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:posts, [:post_name], name: "posts_unique_post_name_index")

    create table(:post_meta, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:meta_key, :text, null: false)
      add(:meta_value, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :post_id,
        references(:posts,
          column: :id,
          name: "post_meta_post_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:options, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:option_name, :text, null: false)
      add(:option_value, :text, null: false)
      add(:autoload, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:comment_content, :text, null: false)
      add(:comment_author_email, :text, null: false)
      add(:comment_author_url, :text, null: false)
      add(:comment_author_ip, :text, null: false)
      add(:comment_type, :text, null: false, default: "comment")
      add(:comment_approved, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :comment_author_id,
        references(:users,
          column: :id,
          name: "comments_comment_author_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :comment_post_id,
        references(:posts,
          column: :id,
          name: "comments_comment_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :comment_parent_id,
        references(:comments,
          column: :id,
          name: "comments_comment_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:comment_meta, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:meta_key, :text)
      add(:meta_value, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :comment_id,
        references(:comments,
          column: :id,
          name: "comment_meta_comment_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:comment_meta, "comment_meta_comment_id_fkey"))

    drop(table(:comment_meta))

    drop(constraint(:comments, "comments_comment_author_id_fkey"))

    drop(constraint(:comments, "comments_comment_post_id_fkey"))

    drop(constraint(:comments, "comments_comment_parent_id_fkey"))

    drop(table(:comments))

    drop(table(:options))

    drop(constraint(:post_meta, "post_meta_post_id_fkey"))

    drop(table(:post_meta))

    drop_if_exists(unique_index(:posts, [:post_name], name: "posts_unique_post_name_index"))

    drop(constraint(:posts, "posts_author_id_fkey"))

    drop(constraint(:posts, "posts_post_parent_fkey"))

    alter table(:posts) do
      remove(:post_parent)
      remove(:author_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:post_content_filtered)
      remove(:post_name)
      remove(:post_password)
      remove(:comment_count)
      remove(:post_mime_type)
      remove(:menu_order)
      remove(:guid)
      remove(:pinged)
      remove(:to_ping)
      remove(:ping_status)
      remove(:comment_status)
      remove(:post_type)
      remove(:post_status)
      remove(:post_excerpt)
      remove(:post_content)
      remove(:post_title)
    end

    drop(constraint(:term_relationships, "term_relationships_post_id_fkey"))

    alter table(:term_relationships) do
      modify(:post_id, :uuid)
    end

    drop(table(:posts))

    drop(constraint(:term_meta, "term_meta_term_id_fkey"))

    drop(table(:term_meta))

    drop(constraint(:term_relationships, "term_relationships_term_taxonomy_id_fkey"))

    drop(table(:term_relationships))

    drop(constraint(:term_taxonomy, "term_taxonomy_term_id_fkey"))

    drop(constraint(:term_taxonomy, "term_taxonomy_parent_id_fkey"))

    drop(table(:term_taxonomy))

    drop_if_exists(unique_index(:terms, [:slug], name: "terms_unique_slug_index"))

    drop(table(:terms))

    drop(table(:tokens))

    drop(constraint(:user_meta, "user_meta_user_id_fkey"))

    drop(table(:user_meta))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    drop_if_exists(unique_index(:users, [:display_name], name: "users_unique_display_name_index"))

    drop(table(:users))
  end
end
