defmodule Monorepo.Repo.Migrations.WithIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:user_meta, [:meta_key, :user_id],
             name: "user_meta_meta_key_with_user_id_index"
           )

    create unique_index(:post_meta, [:meta_key, :post_id],
             name: "post_meta_meta_key_with_post_id_index"
           )

    create unique_index(:comment_meta, [:meta_key, :comment_id],
             name: "comment_meta_meta_key_with_comment_id_index"
           )

    create unique_index(:term_meta, [:term_id, :term_key],
           name: "term_meta_term_meta_key_with_term_id_index"
         )
  end

  def down do
    drop_if_exists(
      unique_index(:comment_meta, [:meta_key, :comment_id],
        name: "comment_meta_meta_key_with_comment_id_index"
      )
    )

    drop_if_exists(
      unique_index(:post_meta, [:meta_key, :post_id],
        name: "post_meta_meta_key_with_post_id_index"
      )
    )

    drop_if_exists(
      unique_index(:user_meta, [:meta_key, :user_id],
        name: "user_meta_meta_key_with_user_id_index"
      )
    )

    drop_if_exists(
      unique_index(:term_meta, [:term_id, :term_key],
        name: "term_meta_term_meta_key_with_term_id_index"
      )
    )
  end
end
