defmodule Monorepo.Repo.Migrations.AddPostDate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify(:post_name, :text, null: true, default: nil)
      add(:post_date, :utc_datetime, null: false, default: fragment("'2025-01-03 06:11:17Z'"))
    end
  end

  def down do
    alter table(:posts) do
      remove(:post_date)
      modify(:post_name, :text, null: false, default: "")
    end
  end
end
