defmodule Moly.Repo.Migrations.Create do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX meta_value_idx ON post_meta (substring(meta_value FROM 1 FOR 12));
    """)
  end

  def down do
    execute("""
    DROP INDEX meta_value_idx;
    """)
  end
end
