defmodule Monorepo.Repo.Migrations.Modify do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:term_taxonomy, "term_taxonomy_parent_id_fkey"))

    alter table(:term_taxonomy) do
      modify(:description, :text, null: true, default: "")

      modify(
        :parent_id,
        references(:terms,
          column: :id,
          name: "term_taxonomy_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:posts) do
      modify(:post_date, :utc_datetime, default: nil)
    end
  end

  def down do
    alter table(:posts) do
      modify(:post_date, :utc_datetime, default: fragment("'2025-01-03 06:11:17Z'"))
    end

    drop(constraint(:term_taxonomy, "term_taxonomy_parent_id_fkey"))

    alter table(:term_taxonomy) do
      modify(
        :parent_id,
        references(:term_taxonomy,
          column: :id,
          name: "term_taxonomy_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(:description, :text, null: false, default: nil)
    end
  end
end
