defmodule Moly.Repo.Migrations.AddPostStatusIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:posts, [:post_status], name: "post_status_idx")
  end

  def down do
    drop_if_exists(index(:posts, [:post_status], name: "post_status_idx"))
  end
end
