defmodule Moly.Repo.Migrations.TermMetaUniqueIndex1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:term_meta, [:term_id, :term_key, :term_value],
        name: "term_meta_term_key_value_index"
      )
    )

    create unique_index(:term_meta, [:term_key, :term_value],
             name: "term_meta_term_key_value_index"
           )

    create unique_index(:term_meta, [:term_id, :term_key, :term_value],
             name: "term_meta_term_key_value_with_id_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:term_meta, [:term_id, :term_key, :term_value],
        name: "term_meta_term_key_value_with_id_index"
      )
    )

    drop_if_exists(
      unique_index(:term_meta, [:term_key, :term_value], name: "term_meta_term_key_value_index")
    )

    create unique_index(:term_meta, [:term_id, :term_key, :term_value],
             name: "term_meta_term_key_value_index"
           )
  end
end
