defmodule Monorepo.Repo.Migrations.WithIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:term_meta, [:term_id, :term_key],
             name: "term_meta_term_meta_key_with_term_id_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:term_meta, [:term_id, :term_key],
        name: "term_meta_term_meta_key_with_term_id_index"
      )
    )
  end
end
