defmodule Moly.Repo.Migrations.Remove do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:term_meta, [:term_key, :term_value], name: "term_meta_term_key_value_index")
    )
  end

  def down do
    create unique_index(:term_meta, [:term_key, :term_value],
             name: "term_meta_term_key_value_index"
           )
  end
end
