defmodule Moly.Repo.Migrations.PostCreateIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX pgweb_idx ON posts USING GIN (to_tsvector('english', post_title || ' ' || post_content));
    """)
  end

  def down do
    execute("""
    DROP INDEX pgweb_idx;
    """)
  end
end
