defmodule Moly.Repo.Migrations.PostMeteUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:post_meta, [:meta_key, :post_id],
        name: "post_meta_meta_key_with_post_id_index"
      )
    )

    create unique_index(:post_meta, [:meta_key, :meta_value, :post_id],
             name: "post_meta_meta_key_value_with_post_id_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:post_meta, [:meta_key, :meta_value, :post_id],
        name: "post_meta_meta_key_value_with_post_id_index"
      )
    )

    create unique_index(:post_meta, [:meta_key, :post_id],
             name: "post_meta_meta_key_with_post_id_index"
           )
  end
end
