defmodule Monorepo.Repo.Migrations.TermUniqueNameSlug do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(unique_index(:terms, [:slug], name: "terms_unique_slug_index"))

    create unique_index(:terms, [:name, :slug], name: "terms_unique_name_slug_index")
  end

  def down do
    drop_if_exists(unique_index(:terms, [:name, :slug], name: "terms_unique_name_slug_index"))

    create unique_index(:terms, [:slug], name: "terms_unique_slug_index")
  end
end
