defmodule Moly.Repo.Migrations.ReferencesRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:term_relationships, "term_relationships_post_id_fkey"))

    alter table(:term_relationships) do
      modify(
        :post_id,
        references(:posts,
          column: :id,
          name: "term_relationships_to_posts_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all,
          on_update: :update_all
        )
      )
    end
  end

  def down do
    drop(constraint(:term_relationships, "comments_to_posts_fkey"))

    alter table(:term_relationships) do
      modify(
        :post_id,
        references(:posts,
          column: :id,
          name: "term_relationships_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end
end
