defmodule Monorepo.Repo.Migrations.TermRelationshipsUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:term_relationships, [:term_taxonomy_id, :post_id],
             name: "term_relationships_post_id_term_taxonomy_id_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:term_relationships, [:term_taxonomy_id, :post_id],
        name: "term_relationships_post_id_term_taxonomy_id_index"
      )
    )
  end
end
