defmodule Monorepo.Repo.Migrations.TaxonomyTermId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:term_taxonomy, [:term_id, :taxonomy],
             name: "term_taxonomy_taxonomy_term_id_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:term_taxonomy, [:term_id, :taxonomy],
        name: "term_taxonomy_taxonomy_term_id_index"
      )
    )
  end
end
