defmodule Monorepo.Repo.Migrations.CreateUserPostAction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_post_actions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:action, :text, null: false)

      add(:created_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "user_post_actions_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :post_id,
        references(:posts,
          column: :id,
          name: "user_post_actions_post_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:user_post_actions, "user_post_actions_user_id_fkey"))

    drop(constraint(:user_post_actions, "user_post_actions_post_id_fkey"))

    drop(table(:user_post_actions))
  end
end
