defmodule Monorepo.Repo.Migrations.ModifyUserMeta do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_meta) do
      modify(:meta_value, :text, null: true)
    end
  end

  def down do
    alter table(:user_meta) do
      modify(:meta_value, :text, null: false)
    end
  end
end
