defmodule Monorepo.Repo.Migrations.RemoveUserFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove(:avatar)
      remove(:display_name)
      remove(:nickname)
    end

    drop_if_exists(unique_index(:users, [:display_name], name: "users_unique_display_name_index"))

    alter table(:terms) do
      modify(:slug, :text, null: true)
    end

    alter table(:term_relationships) do
      modify(:term_order, :bigint, null: true)
    end
  end

  def down do
    alter table(:term_relationships) do
      modify(:term_order, :bigint, null: false)
    end

    alter table(:terms) do
      modify(:slug, :text, null: false)
    end

    create unique_index(:users, [:display_name], name: "users_unique_display_name_index")

    alter table(:users) do
      add(:nickname, :text)
      add(:display_name, :text)
      add(:avatar, :text)
    end
  end
end
