defmodule Monorepo.Repo.Migrations.UserActionUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:user_post_actions, [:user_id, :post_id, :action],
             name: "user_post_actions_unique_user_id_post_id_action_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:user_post_actions, [:user_id, :post_id, :action],
        name: "user_post_actions_unique_user_id_post_id_action_index"
      )
    )
  end
end
