name: Build and Push Docker Images

on:
  push:
    branches:
      - affinew
  pull_request:
    branches:
      - affinew

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images for amd64 and arm64
      - name: Build and push multi-arch Docker image
        run: |
          # Enable experimental features in Docker CLI (for Buildx)
          export DOCKER_CLI_EXPERIMENTAL=enabled
          
          # Build and push for multiple architectures (amd64 and arm64)
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/moly:${{ github.ref_name }} . --push
          
        # This step will use the Docker setup from setup-buildx-action
