jobs:
  build-and-push:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Enable GHA cache backend
          buildx-flags: --cache-to type=gha,mode=max --cache-from type=gha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/moly:${{ github.ref_name }}
          # When using type=gha, you don't need to specify cache-from/to here
          # as it's handled by buildx-flags in setup-buildx-action
          # cache-from: |
          #   type=local,src=/tmp/.buildx-cache-arm64
          # cache-to: |
          #   type=local,dest=/tmp/.buildx-cache-arm64,mode=max,platform=linux/arm64