name: Build and Push Docker Images

on:
  push:
    branches: [ affinew ]
  pull_request:
    branches: [ affinew ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            platform:
              - linux/amd64
              - linux/arm64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/moly:${{ github.ref_name }}