name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: macos-latest # 这是 ARM64 runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- 关键修改：使用 docker/setup-docker@v3 替代旧的 action ---
      - name: Setup Docker
        uses: docker/setup-docker@v3 # 使用官方推荐的 Docker 设置 Action
        # docker/setup-docker@v3 通常不需要额外的 with 参数
        # 它会根据 runner 自动设置合适的 Docker 版本和环境。
        # 如果需要特定版本，可以使用 with: version: '24.0.0' 或 'latest'，
        # 但通常默认行为在 macOS ARM64 上运行良好。

      - name: Verify Docker installation
        run: |
          docker --version
          docker info

      # 移除 Set up QEMU (因为 macos-latest 是 ARM64，构筑 linux/arm64 不需要模拟)
      # 但要确保 Buildx 依然启用，因为它提供了更好的构建能力。
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers for arm64
        id: cache-arm64
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-arm64
          key: ${{ runner.os }}-docker-arm64-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-arm64-

      - name: Build and Push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/moly:${{ github.ref_name }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache-arm64
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-arm64,mode=max,platform=linux/arm64